apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-env
data:
  HOST: "0.0.0.0"
  PORT: "3080"
  DOMAIN_CLIENT: "https://cto.ascendingdc.com"
  DOMAIN_SERVER: "https://cto.ascendingdc.com"
  NO_INDEX: "true"
  CONSOLE_JSON: "false"
  DEBUG_LOGGING: "true"
  DEBUG_CONSOLE: "false"
  SEARCH: "true"
  MEILI_NO_ANALYTICS: "true"
  MEILI_HOST: "http://meilisearch:7700"
  DEBUG_PLUGINS: "true"
  ALLOW_EMAIL_LOGIN: "true"
  ALLOW_REGISTRATION: "true"
  ALLOW_SOCIAL_LOGIN: "true"
  ALLOW_SOCIAL_REGISTRATION: "true"
  ALLOW_PASSWORD_RESET: "true"
  ALLOW_ACCOUNT_DELETION: "true"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "false"
  ALLOW_SHARED_LINKS: "true"
  ALLOW_SHARED_LINKS_PUBLIC: "true"
  Q_BUSINESS_API_BASE_URL: "http://q-business-api-service:8080/v1/chat/completions"
  RAG_PORT: "8000"
  RAG_API_URL: "http://rag-api:8000"
  APP_TITLE: "AskCTO: AI Solution Architect"
  CUSTOM_FOOTER: "[ASCENDING](https://ascendingdc.com/industries/smb) | Messy World,Clean Code!"
  HELP_AND_FAQ_URL: "https://ascendingdc.com/contact-us?m=SMB%20Inquiry:%20Additional%20help%20from%20AskCTO&p=/industry/smb"
  EMAIL_SERVICE: "sendgrid"
  EMAIL_HOST: "smtp.sendgrid.net"
  EMAIL_PORT: "587"
  EMAIL_ENCRYPTION: "TLS"
  EMAIL_USERNAME: "apikey"
  EMAIL_PASSWORD: ""
  EMAIL_FROM_NAME: "AskCTO-ASCENDING"
  EMAIL_FROM: "noreply@ascendingdc.com"
  GOOGLE_CLIENT_ID: "666529608902-3c754d36dhkrpt7t9lrvuave94a2rfm7.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_CALLBACK_URL: "/oauth/google/callback"
  ENDPOINTS: "custom"
